import Head from 'next/head'
import { useState, useEffect } from 'react'
import Characters from '../Components/Characters'
import Hero from '../Components/Hero'
import MultiChars from '../Components/MultiChars'



export default function Home() {

  //get multiple characters 1, 2, 3,4 
  const [characters, setCharacters] = useState([])
  const [randomNumbers, setRandomNumbers] = useState(Math.floor(Math.random() * 10) + 1)
  const [multiChars, setMultiChars] = useState([])
  const [query, setQuery] = useState('/1,83,20')


  //url
  const [url, setUrl] = useState('https://rickandmortyapi.com/api/character')

  useEffect(() => {  
    const fetchMultiChars = async ()  => {
      let data = await fetch(url)
      const characters = await data.json()
      //set characters
      const {info, results } = characters
      setCharacters(results)
      
    }
    //fetch data
    fetchMultiChars()
   
  }, [url])

 

  //get random numbers from 1 - 5
  const randomNumber = () => {
    const random = Math.floor(Math.random() * 10) + 1
    return random
  }

  const getMultiCharacter = () => {
    let temp = characters.filter((char, index) => {
      if(index > 1 && index < 5){
       return char
      }
    })
    console.log(temp);
    setMultiChars(temp);
  }




  return (
    <div className='Main-content'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
      <MultiChars characters={characters}/> 
    </div>
  )
}
