import Head from 'next/head'
import { useState, useEffect } from 'react'
import Characters from '../Components/Characters'
import Hero from '../Components/Hero'

export default function Home() {
  //state for multiple charactes
  const [multiChars, setMultiChars] = useState([])

  //url to tet multiple characters
  const url = 'https://rickandmortyapi.com/api/character/1,183,20'

  useEffect(() => {  
    const fetchMultiChars = async ()  => {
      let response = await fetch(url)
      const characterData = await response.json()
      console.log(characterData);
      //set characterData
      setMultiChars(characterData)
      
    }
    //fetch data
    fetchMultiChars()
   
  }, [])

  return (
    <div className='Main-content'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
      <Characters characters={multiChars}/> 
    </div>
  )
}
